### PR TITLE
Update to new planckton schema

### LINKED ISSUE #1: Need a function to get ref values from the force field
With the new updates to [unit_conversions](https://github.com/cmelab/planckton/blob/master/planckton/utils/unit_conversions.py), a function is needed to obtain the reference values from the force field.
I think `ref_values` in `Simulation.run` should be enough.

### LINKED ISSUE #3: only support parameter entry in reduced units
add SI T to job doc (see uli-init)

### PR DESCRIPTION
**Pull request by jennyfothergill**
fixes #3 (SI_kT example is removed) and fixes #1 (https://github.com/cmelab/planckton/pull/33)

Before merging I will

- [x]  set up CI
- [x] test this on Fry

### CODE REVIEW

**Comment by jennyfothergill** [comment]
I'm having difficulty getting this to work on Fry. Here's what I've done:
1. I've installed planckton-flow requirements on Fry. (gsd, signac, signac-flow)
2. I've cloned planckton-flow (and planckton, but it should be unnecessary)
2. I've pulled the latest singularity image and assigned its location to the variable $PLANCKTON_SIMG
3. In planckton-flow, `python src/init.py` runs without issue
4. When I try to run `python src/project.py submit`, I get the error that the unyt package is not found.
5. I know that unyt is in the container because this command works `singularity exec $PLANCKTON_SIMG python test_local.py` and `singularity exec $PLANCKTON_SIMG python -c "import unyt"` also works; however, running `python -c "import unyt"` in the shell accessed with `singularity exec $PLANCKTON_SIMG bash` gives an error.

**Comment by jennyfothergill** [comment]
OK this is working! With commit f276630 I think we may no longer need the `{% set cmd_prefix = "singularity exec --nv --bind $(pwd) $PLANCKTON_SIMG " %}` line in the submission templates.

**Comment by chrisjonesBSU** [comment]
I have a few comments about the instructions.

1. We should also make a comment about adding the `PLANCKTON_SIMG` variable to a .bashrc file so it won't have to be ran every time.

2. Even though there are only a few packages, I think it would be helpful to still have the user create a conda environment which includes the required python version. As the instructions are written now, the user might try to submit jobs where `python` is version 2.7 or an older python 3 version.

3. Be more explicit about where to run the `singularity pull` command. If someone were reading the instructions step-by-step they would be running that command after changing into the `planckton-flow` repo.

**Comment by jennyfothergill** [comment]
@chrisjonesBSU good ideas! I think I've added all of them in the latest commit.

**Pull request merged**
