### PR TITLE
Use cluster specific walltime variable

### PR DESCRIPTION
**Pull request by chrisjonesBSU**

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
Ok, I think this is ready. I fixed the location of the hoomd walltime env variable in all of cluster .sh files. I added it one for bridges2 (I believe their default wall time is 24 hours). Also, I removed `kestrel.sh`

**Review by jennyfothergill — COMMENTED** [review]
Thanks @chrisjonesBSU for taking the time to look into this!
We should remove Kestrel from the supported clusters in the README.
We might also want to add the `SBATCH -t {{ whatever_time|format_timedelta }}` to r2 and borah.

**Comment by chrisjonesBSU** [comment]
Ok, I removed Kestrel from the README as well as from `project.py`. I believe the `SBATCH -t` line is already in both the r2 and borah .sh files.

**Review by jennyfothergill — APPROVED** [review]
Yep, so it is! 🤦‍♀️ 
LGTM!

**Pull request merged**
